version: '3'
services:

  caddy:
    image: caddy:2.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config


  database:
    image: postgis/postgis:13-master
    restart: always
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      # POSTGRES_DB: 'directus'
      POSTGRES_DB_FILE: '/run/secrets/database_password'
    secrets:
      - database_password
  cache:
    restart: always
    image: redis:6

  directus:
    # build: ./directus
    image: directus/directus:10.7.1
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./directus/extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      # SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      SECRET_FILE: '/run/secrets/directus_secret'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      # DB_PASSWORD: 'directus'
      DB_PASSWORD_FILE: '/run/secrets/database_password'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      # ADMIN_PASSWORD: 'd1r3ctu5'
      ADMIN_PASSWORD_FILE: '/run/secrets/admin_directus_password'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
      PUBLIC_URL: 'https://demo.tryphon.online'
      LOG_LEVEL: 'error'

    secrets:
      - database_password
      - directus_secret
      - admin_directus_password

secrets:
  database_password:
    file: ./secrets/database_password
  directus_secret:
    file: ./secrets/directus_secret
  admin_directus_password:
    file: ./secrets/admin_directus_password